name: example-environment
channels:
  - conda-forge
dependencies:
  - conda env export -n <env-name> 
  - pandas
  - geopandas
  - pyodbc
  - bokeh
  - sqlalchemy
  - ipython-sql
  - matplotlib
  - numpy
